### ISSUE TITLE
Flame not working

### ISSUE THREAD

**Issue by doliG** [Kingfisher7/Dragon-Fire-syntax#1]
All is in the title.
![image](https://user-images.githubusercontent.com/24778042/32903034-40f41ee0-caf4-11e7-9c6b-17ee4a69d7fd.png)

**Comment by Bingbazaar** [comment]
Hello!
Thank you so much for bringing this to my concern.
I have updated the theme. Could you install the update from Atom, then restart Atom, and see if it works then?

If it doesn't work, could you please open the console in Atom by going to View -> Developer -> Toggle Developer tools, clicking "Console" and then looking at what path it's trying to find the flame.gif file?

**Comment by Bingbazaar** [comment]
Ok I realized it's not going to work now. I'll try to fix it tomorrow.

The problem is that I'm trying to load a flame in base.less, but when just using url('./flame.gif') in the right repository. I tried to work around this but I guess the workaround wasn't foolproof.

**Comment by Bingbazaar** [comment]
I uploaded a patch. Could you install the update, restart Atom and confirm that it is working @doliG?

**Comment by doliG** [comment]
Hello @Kingfisher7 

Great work, it's working now :)

Thanks you !

**Comment by Bingbazaar** [comment]
Yay! Thank you too! 
Enjoy! :)
